---
abstract: 'HTTP::MobileAgent plugin for Amon2'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Amon2-Plugin-Web-MobileAgent
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Amon2::Plugin::Web::MobileAgent:
    file: lib/Amon2/Plugin/Web/MobileAgent.pm
    version: 0.07
  Amon2::Plugin::Web::MobileCharset:
    file: lib/Amon2/Plugin/Web/MobileCharset.pm
    version: 0
  Amon2::Setup::Flavor::MobileJP:
    file: lib/Amon2/Setup/Flavor/MobileJP.pm
    version: 0
requires:
  Amon2: 3.03
  Encode::JP::Mobile: 0.29
  HTTP::MobileAgent: 0
  HTTP::MobileAgent::Plugin::Charset: 0
  Lingua::JA::Regular::Unicode: 0
  perl: v5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
