---
abstract: 'HTTP::MobileAgent plugin for Amon2'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Amon2-Plugin-Web-MobileAgent
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Amon2: 3.01
  Encode::JP::Mobile: 0
  HTTP::MobileAgent: 0
  HTTP::MobileAgent::Plugin::Charset: 0
  Lingua::JA::Regular::Unicode: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
